env:
  global:
    - SWIFT_BRANCH=swift-4.2-branch
    - SWIFT_VERSION=swift-4.2-DEVELOPMENT-SNAPSHOT-2018-08-25-a
matrix:
  include:
    - os: linux
      name: "Linux"
      language: generic
      dist: trusty
      sudo: required
      install:
        - sudo apt-get install clang libicu-dev
        - mkdir swift
        - curl https://swift.org/builds/$SWIFT_BRANCH/ubuntu1404/$SWIFT_VERSION/$SWIFT_VERSION-ubuntu14.04.tar.gz -s | tar xz -C swift &> /dev/null
        - export PATH="$(pwd)/swift/$SWIFT_VERSION-ubuntu14.04/usr/bin:$PATH"
      script:
        - swift package update
        - swift test --generate-linuxmain
        - swift test

    - os: osx
      name: "macOS"
      language: swift
      sudo: required
      install:
        - gem install xcov # For codecoverage
        - gem install fastlane
      script:
        - swift package install
          # CodeCoverage report generation (use "swift test" otherwise)
        - swift package generate-xcodeproj
        - fastlane scan --code_coverage
          #- xcodebuild test -scheme Test -enableCodeCoverage YES
        - xcov
after_success:
  - bash <(curl -s https://codecov.io/bash)
